# IBM Cloud
region: eu-gb
prefix: mcpgw
k8s_workers: 1
cluster_flavor: bx2.4x16
kube_version: "1.29"

# Databases
postgres_version: "17"
redis_version: "7"

# Application
gateway_image: "ghcr.io/jrmatherly/mcp-context-forge"
gateway_image_tag: "v1.0.0rc1"
chart_version: "1.0.0-rc.1"
gateway_replicas: 2
ingress_class: public-iks-k8s-nginx

# Feature flags
auth_required: true
plugins_enabled: true
